# Default values for system-upgrade-contoller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespace created on installation
targetns: system-upgrade

controller:
  image: rancher/system-upgrade-controller
  version:  v0.13.0

# if install eq true 2 sample plans will installed 
plan:
  install: false
  image: rancher/k3s-upgrade
  version: v1.24.6+k3s1